[package]
name = "rust_os"
version = "0.1.0"
authors = ["Phillip Oppermann <dev@phil-opp.com>, Ryan Campbell <rdcampbell1990@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0"
volatile = "0.1.0"
spin = "0.4.5"
multiboot2 = "0.1.0"
bitflags = "0.7.0"
x86_64 = "0.1.2"